name: build-project
on:
    push:
        branches:
            - master
jobs:
    build-an-app:
        runs-on: ubuntu-latest
        steps:
            - name: get the project code
              uses: actions/checkout@v4
            - name: file path
              run: ls -ltr
            - name: install the application
              run: npm install
            - name: start the application
              run: npm start
